apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: enterprise-alert-agent-data
  namespace: enterprise-alert
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
